# Generated by Django 4.0.3 on 2022-03-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalmeereboer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='newsimages/'),
        ),
    ]
