# Generated by Django 4.0.3 on 2022-03-31 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stalmeereboer', '0002_post_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hengst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hengst_title', models.CharField(max_length=100)),
                ('hengst_image', models.ImageField(blank=True, null=True, upload_to='hengstimages/')),
                ('hengst_content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
